FROM vital987/vubuntu-purevnc:latest
RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -P /tmp && \
apt-get install --no-install-recommends -y /tmp/google-chrome-stable_current_amd64.deb && \
apt-get --fix-broken install -y
